### PR TITLE
pattern TypeScript changes

### PR DESCRIPTION
**Pull request by jaslong**
This package is amazing, thank you!

I am using it with TypeScript and have some improvements:
- Add top-level "types" field to package.json. Some tools may only use the "types" field instead of "exports". For example, I was simply using `tsc` to check types and it couldn't resolve the package without the field. **edit: Separated this change to https://github.com/slevithan/regex/pull/23 since the conversation in this PR is focused on pattern usage.**
- Fix `pattern` substitutions type to match `regex`. I was trying to use patterns nested in other patterns, but currently the `pattern` `substitutions` type only allows strings. I updated it to match the `InterpolatedValue` in `regex`.

### CODE REVIEW

**Comment by slevithan** [comment]
Thanks, @jaslong!

I'd love to better understand how these changes help.

> Add top-level "types" field to package.json. Some tools may only use the "types" field instead of "exports". For example, I was simply using `tsc` to check types and it couldn't resolve the package without the field.

The config is relatively simple right now and I'd love to keep it as simple as possible. So, it would be helpful to better understand use cases / specific examples of other tools it would help. For example, can you share your `tsc` command that wasn't working without this change? (I'm new to TypeScript.)

> Fix `pattern` substitutions type to match `regex`. I was trying to use patterns nested in other patterns, but currently the `pattern` `substitutions` type only allows strings. I updated it to match the `InterpolatedValue` in `regex`.

The current types are intentional. Can you explain a use case and show an example for why/how you would interpolate a `pattern` within another `pattern`? Why not interpolate a string in the `pattern`, or interpolate multiple `pattern`s in the `regex`?

I appreciate you helping to make things better!

**Comment by jaslong** [comment]
I was just using `tsc` on my own project which depends on `regex`. I am currently on `tsc` 4.7.4. Here's the errors I get:

```
$ tsc --noEmit
src/redacted:21:23 - error TS2307: Cannot find module 'regex' or its corresponding type declarations.
21 import { regex } from "regex";
                         ~~~~~~~
src/redacted.ts:5:32 - error TS2307: Cannot find module 'regex' or its corresponding type declarations.
5 import { pattern, regex } from "regex";
                                 ~~~~~~~
src/redacted.ts:1:32 module 'regex' or its corresponding type declarations.
1 import { pattern, regex } from "regex";
                                 ~~~~~~~
```

**Comment by jaslong** [comment]
I have some complex regexes that I'm trying to create, and regex is really improving the readability a lot. Here's an example, let me know if this is the best way to do such a scenario:

```typescript
// This module exports regexes for matching valid identifiers in JS code.
// The regexes are built on of each other, so I want to reduce repetition to avoid bugs.

const pJsIdentifierStartChar = pattern`[$_\p{ID_Start}]`;
export const pJsIdentifierChar = pattern`[$\u200c\u200d\p{ID_Continue}]`;

/**
 * Matches an entire valid identifier.
 *
 * Regular expression for a valid identifier, according to MDN (with `u` flag)
 * [$_\p{ID_Start}][$\u200c\u200d\p{ID_Continue}]*
 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#identifiers
 */
export const pJsIdentifier = pattern`${pJsIdentifierStartChar}${pJsIdentifierChar}*`;
export const reJsIdentifierExact = re('g')`^${pJsIdentifier}$`;
```

**Comment by jaslong** [comment]
Related to the above example, can you confirm if this is impossible due to compatibility reasons?

I want to export the below regexes, with code like this:

```
export const pJsIdentifierChar = pattern`[]`;
export const pNotJsIdentifierChar = pattern`[^$\u200c\u200d\p{ID_Continue}]`;
```

// They are both character classes, but one is the negation of the other.
// I wanted to reuse the contents of the character class
// `$\u200c\u200d\p{ID_Continue}`
// but I got the error
// "Invalid nested character class when flag v not supported; possibly from interpolation"

```
export const pJsIdentifierChar = pattern`[$\u200c\u200d\p{ID_Continue}]`;
export const pNotJsIdentifierChar = pattern`[^$\u200c\u200d\p{ID_Continue}]`;


// One thing I was not able to do is reuse the contents of the character class
// from `pJsIdentifierChar`.
// `$\u200c\u200d\p{ID_Continue}`
// because of compatibility reasons https://github.com/slevithan/regex#-compatibility
export const pNotJsIdentifierChar = pattern`[^$\u200c\u200d\p{ID_Continue}]`;
```

**Comment by jaslong** [comment]
Related to the above example, can you confirm if this is impossible due to compatibility reasons?

I want to export the below regexes, with code like this:

```
const charClassContent = pattern`$\u200c\u200d\p{ID_Continue}`;
export const pJsIdentifierChar = pattern`[${charClassContent}]`;
export const pNotJsIdentifierChar = pattern`[^${charClassContent}]`;
```

but the library throws the following error when trying to interpret it: "Invalid nested character class when flag v not supported; possibly from interpolation". Is this because of the compatibility reasons listed here? https://github.com/slevithan/regex#-compatibility

And therefore, I'm forced to repeat myself like this?

```
export const pJsIdentifierChar = pattern`[$\u200c\u200d\p{ID_Continue}]`;
export const pNotJsIdentifierChar = pattern`[^$\u200c\u200d\p{ID_Continue}]`;
```

**Comment by slevithan** [comment]
Thanks for the examples! It's super valuable and informative for me to see real-world usage like this.

Here's my take: Exporting `pattern`s seems unnecessary and makes the export less reusable. `pattern` is intended to wrap strings that you want to interpolate without escaping, so I'd recommend just exporting a string, and then using `` regex`${pattern(importedStr)}` `` when you want to use it. So I would do:

```js
const pJsIdentifierStartChar = String.raw`[$_\p{ID_Start}]`;
export const pJsIdentifierChar = String.raw`[$\u200c\u200d\p{ID_Continue}]`;
export const pJsIdentifier = `${pJsIdentifierStartChar}${pJsIdentifierChar}*`;
export const reJsIdentifierExact = regex('g')`^ ${pattern(pJsIdentifier)} $`;
```

> but the library throws the following error when trying to interpret it: "Invalid nested character class when flag v not supported; possibly from interpolation". Is this because of the compatibility reasons listed here? https://github.com/slevithan/regex#-compatibility

Yes.

It's possible to make `regex` support nested character classes (which `regex` relies on for sandboxing and atomization when interpolating more than one character node at a time *within* character classes) in environments without support for flag `v` by providing your own `unicodeSetsPlugin` (see [Options](https://github.com/slevithan/regex#-options)). But I don't expect most people to do this. And, technically, in future versions I could update `regex` to make your example work when flag `v` isn't supported natively, but such a solution wouldn't be comprehensive (still might be worth pursuing, though) because to follow `regex`'s interpolation rules it must use nested classes when interpolating at a position in a character class that borders a range operator or set operation (which doesn't apply in your case).

Fortunately, there's an easy workaround without repeating yourself: Only use one `pattern` (that contains the entire character class) and interpolate or pass strings into it. Ex:

```js
const charClassContent = String.raw`$\u200c\u200d\p{ID_Continue}`;
export const pJsIdentifierChar = String.raw`[${charClassContent}]`;
export const pNotJsIdentifierChar = String.raw`[^${charClassContent}]`;

// And then...
regex`${pattern(pNotJsIdentifierChar)}`

// Or, if you didn't actually need the `pNotJsIdentifierChar` export
regex`${pattern(`[^${charClassContent}]`)}`
```

**Comment by jaslong** [comment]
Thanks for the detailed response!

Could you help explain how using `pattern` is less reusable? Also, when using `pattern`, the variable is of class `Pattern`, so I know it shouldn't be used as a normal string. This makes it more self-documenting.

**Comment by slevithan** [comment]
> Could you help explain how using `pattern` is less reusable?

Only due to possible type restrictions in other code that you might want to reuse the strings with. Apart from that, I guess since `Pattern` instances coerce to strings, its not actually less reusable. But yeah, `pattern` interpolation has just such a type restriction, which this PR addresses but I'm still not sure about the change.

> Also, when using `pattern`, the variable is of class `Pattern`, so I know it shouldn't be used as a normal string. This makes it more self-documenting.

The self-documenting aspect is nice, I admit. But it's tricky-ish to use it that way right now anyway since `regex` intentionally doesn't export the `Pattern` class. And I'd also be wary about a change that exports it, for the same reason I'm wary about using types to endorse interpolating patterns into patterns. Namely, `pattern` is meant for interpolation into `regex`; not to introduce a new type that other code relies on. I could be convinced that this is needlessly restrictive, but I'd want to be thoughtful about this and probably would need to see more use cases.

> I was just using `tsc` on my own project which depends on `regex`. I am currently on `tsc` 4.7.4. Here's the errors I get:
>
> ```
> $ tsc --noEmit
> src/redacted:21:23 - error TS2307: Cannot find module 'regex' or its corresponding type declarations.
> 21 import { regex } from "regex";
>                          ~~~~~~~
> ```

Okay, I managed to reproduce this in a project with `moduleResolution` set to `"Node"` in `tsconfig.json`. Setting it to `"NodeNext"` or `"Node16"` fixes it. But yeah, some projects might not be able to make this change. Adding the `"types"` field to `regex`'s `package.json` seems like a good idea for compatibility -- so thank you! If you remove the changes to `src/pattern.js`, I'll go ahead and merge the PR.

**Comment by slevithan** [comment]
> If you remove the changes to `src/pattern.js`, I'll go ahead and merge the PR.

I now see you created a separate PR for that with #23. Thanks! Merged.

As for the `pattern` type changes, this discussion was really informative (thank you!) but I'm no closer to thinking this is a good idea, and I'm leaning toward closing this. What do you think? Has this discussion and the examples changed your mind at all? Or at least made this seem less necessary?

**Comment by jaslong** [comment]
I think I understand the purpose of `pattern` now, and I understand your concerns about exposing `Pattern` as a type.

That said, I do think there's value for some sort of intermediate regex type. But I don't know what the right API and semantics are yet. I'll play around with some abstractions in my own code for now and will share back if I learn anything useful.

**Comment by slevithan** [comment]
Cool, I'll go ahead and close this for now, but I'm happy to reopen it if you have additional thoughts on the subject.

> That said, I do think there's value for some sort of intermediate regex type.

Your language here is great, and useful for me talking more clearly about it (I might update the readme based on this). To state the issue more clearly (mostly for myself, since I think we're already on the same page): As of today, `pattern` is not an intermediate regex type, but just a string wrapper that lets `regex` know your intention (namely, you want the string to be treated as a partial pattern rather than as a string to be matched literally).

> But I don't know what the right API and semantics are yet. I'll play around with some abstractions in my own code for now and will share back if I learn anything useful.

Cool. I'd definitely be interested in what you learn.

That said, I think the starting point for making related changes to the library should be clearly identifying use cases. The two existing intermediate types are strings and regexes. Regexes are a very useful intermediate type since they have their own local flags and independent capture numbers (though they also come with some [restrictions on placement](https://github.com/slevithan/regex#interpolation-contexts)).

A clear use case you've already identified is making code self-document that particular strings are meant to be used as fragments of regex patterns. Of course, that can be indicated in other ways, such as via variable names/conventions. But like I mentioned, I'm not shutting down the idea that the `Pattern` class should have first class support for this--I just want to see stronger/additional use cases for it and/or more demand from users. But regardless, I think it's important that `pattern`/`Pattern` not have special handling for interpolating regexes (or endorsing this through its types), because I consider the context-awareness of all interpolation in the `regex` library to be a core feature. Supporting the interpolation of regexes within patterns would therefore mean handling local flags, syntax context, etc. (things that the `regex` tag already does, so this would be a redundant API that makes intended usage murkier).

**Comment by slevithan** [comment]
Because I consider the context-awareness of all interpolation in the `regex` library to be a core feature, if `pattern` were to be treated as an intermediate regex type and allow interpolation of regexes and patters, it would imply:

- Interpolated regexes within patterns would have their local flags, syntax context, numbered backreferences, etc. respected.
- Interpolated patterns within patterns would have special handling for ensuring that the nested pattern can't change the meaning or error status of tokens in the surrounding pattern.

These features are not out of the question to add, but it would increase the complexity of the "pattern" concept.

**Comment by slevithan** [comment]
Note to self: In the [plasmic](https://github.com/plasmicapp/plasmic) library, @jaslong worked around the type restriction on interpolating patterns into patterns by creating a [custom TypeScript declaration](https://github.com/plasmicapp/plasmic/blob/master/platform/wab/src/wab/shared/utils/regex.d.ts) that imports `types/pattern.d.ts` to access the `Pattern` type, and then used this capability e.g. in [regex-js-identifier.ts](https://github.com/plasmicapp/plasmic/blob/master/platform/wab/src/wab/shared/utils/regex-js-identifier.ts). This is fine, and the interpolated pattern gets coerced to a string with no special handling, as is currently done for all values interpolated into patterns. But it means I need to be extra thoughtful about (and treat as a breaking change) any related changes to handling for interpolation into `pattern` templates, or the way that `regex` currently includes all type declaration files (rather than just `regex.d.ts`) in the npm package (see #8). No related changes are currently planned, so this shouldn't present any problems for the plasmic library (at least in the 4.x line, but quite possibly beyond that as well).

**Pull request closed without merging**
